// ─────────────────────────────────────────────────────────────
// THE WORLD COMPENDIUM — Shared Glory Data
// Single source of truth for index.html and compendium.html
// To add a word: add an entry below in alphabetical order.
// To edit a definition: edit it here — both pages will update.
// 100 entries · Last consolidated: April 19, 2026
// ─────────────────────────────────────────────────────────────

const GLORY_DATA = [
  { word: "Accident", category: "Not Classified",
    definition: "An event that appears to happen on its own — distinct from mistake, coincidence, and fate — yet cause or blame can always be traced to human action, the surrounding conditions, or the laws of physics",
    phonetic: "ak·si·dənt",
    origin: "Latin <em>accidere</em> — 'to fall upon.' From <em>ad-</em> (toward) + <em>cadere</em> (to fall). The word arrived in English through Old French in the 14th century meaning simply 'an event,' without the modern implication of misfortune.",
    howUsed: "Used neutrally for centuries before acquiring its modern association with misfortune and blame. Insurance law, tort law, and media coverage all shape how 'accident' is deployed — often to deflect responsibility. A car 'accident' implies no fault; a car 'crash' implies someone caused it." },

  { word: "American Dream", category: "Origins",
    definition: "The promise that effort equals outcome — more myth than mechanism, more powerful for being neither provably true nor provably false",
    phonetic: "ə·mer·i·kən dreem",
    origin: "Coined by historian James Truslow Adams in 1931 in <em>The Epic of America</em> — during the Depression. Originally meant a social order where each person could achieve the fullest stature of which they are capable, regardless of birth.",
    howUsed: "Quickly narrowed from Adams' broad civic vision to a economic promise: work hard, get ahead, own a home. Used by politicians across the spectrum as shorthand for upward mobility. Increasingly invoked as critique — a myth that justifies inequality by making failure personal." },

  { word: "Belief", category: "Knowledge & Learning",
    definition: "Faith, opinion, or knowledge without proof — often used interchangeably",
    phonetic: "bi·leef",
    origin: "Old English <em>geleafa</em> — trust, confidence. Related to the German <em>Glaube</em>. Rooted in Proto-Germanic words meaning 'to love' or 'to hold dear.' Originally closer to trust in a person than acceptance of a proposition.",
    howUsed: "Flattened over time to mean any held opinion. The phrase 'I believe' now covers everything from theological conviction to preference. The conflation of belief with fact is one of the defining rhetorical moves of contemporary discourse." },

  { word: "Bias", category: "Knowledge & Learning",
    definition: "Everyone has it — only other people are accused of it",
    phonetic: "bī·əs",
    origin: "16th century French <em>biais</em> — oblique, slant. Originally a sewing and bowling term describing a diagonal cut in fabric or the weighted side of a bowl that makes it curve. Entered the language of the mind much later.",
    howUsed: "Expanded from a technical term to a psychological and political one in the 20th century. 'Cognitive bias' entered scientific language in the 1970s. In political use, almost always attributed to others — rarely acknowledged in oneself." },

  { word: "Body", category: "Myself & I",
    definition: "Self, vessel, political terrain, or crime scene — context is everything",
    phonetic: "bod·ee",
    origin: "Old English <em>bodig</em> — trunk of a person or animal. Related to Old High German <em>botah</em>. Original meaning was strictly physical — the trunk separate from the limbs. The spiritual and political dimensions accumulated later.",
    howUsed: "Expanded to carry enormous weight — political terrain, site of law, object of medicine, instrument of labor, subject of art. 'Bodily autonomy,' 'body politic,' 'body count' — the word absorbs whatever the culture needs it to carry." },

  { word: "Border", category: "History & Civilization",
    definition: "Line on a map, security concept, or human rights issue",
    phonetic: "bor·dər",
    origin: "Old French <em>bordure</em> — edge of a shield. From <em>border</em>, to border. Originally referred to the decorative edge of a textile or heraldic device before it became a political term for territorial limits.",
    howUsed: "Militarized and politicized most intensely in the 20th century as nation-states hardened. Before that, borders were porous, contested, and often irrelevant to the people living near them. Today the word carries the full weight of immigration policy, nationalism, and human movement." },

  { word: "Capitalism", category: "Power & Politics",
    definition: "Freedom through markets or organized extraction — still being argued",
    phonetic: "kap·i·tl·iz·əm",
    origin: "From Latin <em>caput</em> — head, chief, principal sum of money. <em>Capital</em> entered English in the 17th century meaning wealth used to produce more wealth. <em>Capitalism</em> as a system-word emerged in the mid-19th century, first used critically by socialist writers.",
    howUsed: "Almost never defined before being invoked. Defenders use it to mean free markets and individual liberty; critics use it to mean exploitation and concentrated ownership. Both are describing real features of the same system." },

  { word: "Censorship", category: "Knowledge & Learning",
    definition: "Suppression of truth or removal of harm — always contested",
    phonetic: "sen·sər·ship",
    origin: "Latin <em>censor</em> — a Roman magistrate who assessed citizens' property and morals. The <em>censor</em>'s role included supervising public conduct and could remove citizens from the rolls for moral failings. The English word entered use in the 16th century.",
    howUsed: "Contested almost entirely at the definitional level — what counts as censorship versus content moderation, editorial judgment, or deplatforming. Who has the power to censor matters enormously. Governments, corporations, and communities all do it differently and call it different things." },

  { word: "Change", category: "Not Classified",
    definition: "Hope or threat depending entirely on what you have to lose",
    phonetic: "chaynj",
    origin: "Old French <em>changier</em> — to alter, exchange. From Late Latin <em>cambiare</em> — to barter. Originally economic before it became existential.",
    howUsed: "'Change' became a political slogan in the 20th century — promising something without specifying what. Obama's 2008 campaign made it explicit. The word is nearly meaningless without context; its power comes from what the listener projects onto it." },

  { word: "Charity", category: "Community & Culture",
    definition: "Generosity, tax strategy, or substitute for justice",
    phonetic: "char·i·tee",
    origin: "Old French <em>charité</em>, from Latin <em>caritas</em> — love, esteem. In early Christian usage it referred to the highest form of love — love of God and neighbor — before narrowing to mean giving money to the poor.",
    howUsed: "Descended from theological virtue to tax category. The gap between its origins (love) and its current function (giving away surplus) is a measure of what the word lost. Critics argue charity substitutes for structural justice; defenders argue it fills gaps the state won't." },

  { word: "Class", category: "Origins",
    definition: "Economic position, cultural identity, or something Americans pretend doesn't exist",
    phonetic: "klas",
    origin: "Latin <em>classis</em> — a division of the Roman people by property for military and tax purposes. Six classes ranked by wealth. The English word retained this structural meaning before it was softened into social 'class' — a category Americans particularly resist.",
    howUsed: "Americans use 'class' as cultural signifier (working class values, upper class manners) more readily than as economic category. The reluctance to discuss economic class structurally is itself a cultural phenomenon — widely noted by sociologists since at least the 1940s." },

  { word: "Community", category: "Origins",
    definition: "Neighborhood, identity group, or abstraction invoked to avoid specifics",
    phonetic: "kə·myoo·ni·tee",
    origin: "Latin <em>communitas</em> — fellowship, from <em>communis</em> — common, shared. Related to <em>commune</em> and <em>communication</em>. Originally implied actual shared life and mutual obligation, not just shared identity.",
    howUsed: "Expanded and hollowed simultaneously. 'The community' now refers to everyone from a ZIP code's residents to a Reddit forum. Used in political speech to imply solidarity without specifying it. 'Community standards,' 'community policing,' 'community college' — each use carries different assumptions." },

  { word: "Constitution", category: "Power & Politics",
    definition: "Living document or fixed text — the entire legal debate in one word",
    phonetic: "kon·sti·too·shən",
    origin: "Latin <em>constitutio</em> — an ordinance, regulation. From <em>constituere</em> — to set up, establish. Originally meant any decree or arrangement. The American Constitution gave the word its modern political weight globally.",
    howUsed: "The central battleground of American legal and political argument. 'The Constitution says' is deployed to end debates that the Constitution actually leaves open. Originalism versus living constitutionalism is ultimately a dispute over whose present the document should serve." },

  { word: "Crime", category: "History & Civilization",
    definition: "Defined by law, which is defined by power",
    phonetic: "krīm",
    origin: "Latin <em>crimen</em> — accusation, fault, offense. From <em>cernere</em> — to decide, to judge. The word carries its judicial origin — crime is not just an act but an act decided to be criminal by a legal process.",
    howUsed: "Defined by statute, which is defined by legislatures, which are shaped by power. What counts as crime shifts with political pressure. The same act — marijuana possession, insider trading, civil disobedience — moves in and out of criminality depending on era and who is doing it." },

  { word: "Crisis", category: "Not Classified",
    definition: "Emergency requiring action or excuse for overreach — both true simultaneously",
    phonetic: "krī·sis",
    origin: "Greek <em>krisis</em> — decision, turning point. From <em>krinein</em> — to decide, to separate. Originally a medical term for the turning point of a disease — the moment it would improve or kill. Carried urgency and decisive action in its original meaning.",
    howUsed: "Inflated through overuse. When everything is a crisis, nothing is. Politicians use crisis to justify emergency powers; media uses it to drive engagement. The word's original precision — a specific decisive moment — has been almost entirely lost." },

  { word: "Culture", category: "Origins",
    definition: "Everything and therefore sometimes nothing",
    phonetic: "kul·chər",
    origin: "Latin <em>cultura</em> — tending, cultivation. From <em>colere</em> — to till, cultivate, worship. Originally agricultural — the tending of land — before transferring to the tending of the mind. <em>Cultura animi</em> — cultivation of the soul — was Cicero's phrase.",
    howUsed: "Expanded until it means nearly everything — and therefore sometimes nothing. 'Culture war,' 'cancel culture,' 'corporate culture,' 'pop culture' — each use implies something different. Anthropologists use it one way; politicians another; marketers a third." },

  { word: "Death", category: "Myself & I",
    definition: "End, transition, or the thing that makes everything else matter",
    phonetic: "deth",
    origin: "Old English <em>dēath</em> — dying, death. Proto-Germanic root related to Old Norse <em>dauði</em>, Gothic <em>dauþus</em>. Among the oldest words in the language — death needed naming before almost anything else.",
    howUsed: "Handled differently across every culture and era. Medicalized in the modern West — moved from home to hospital, from family to professional management. 'Death with dignity,' 'death tax,' 'death panels' — politically loaded in ways that obscure the biological fact." },

  { word: "Debt", category: "Power & Politics",
    definition: "Investment, trap, or moral failing — all three framings in active use",
    phonetic: "det",
    origin: "Latin <em>debitum</em> — that which is owed. Related to <em>debere</em> — to owe. The silent <em>b</em> was reinserted in the 16th century by scholars wanting to honor the Latin root, overriding centuries of spoken English that had dropped it.",
    howUsed: "Carries moral weight beyond the financial — 'in debt' implies obligation and shame in ways that 'owe money' does not. Debt forgiveness invokes this moral dimension. The framing of national debt as household debt is one of the most consequential and contested metaphors in economics." },

  { word: "Defense", category: "History & Civilization",
    definition: "Protection or the budget line item for offense",
    phonetic: "di·fens",
    origin: "Latin <em>defensio</em> — protection, warding off. From <em>defendere</em> — to ward off, protect. The legal sense and the military sense developed simultaneously — both about protecting something from attack.",
    howUsed: "The U.S. Department of War became the Department of Defense in 1947. The renaming is itself a study in how language launders function. Defense spending almost always includes offensive capability; the word frames it otherwise." },

  { word: "Democracy", category: "Power & Politics",
    definition: "Majority rule, representative republic, or failing experiment depending on who's asking",
    phonetic: "di·mok·rə·see",
    origin: "Greek <em>dēmokratia</em> — rule of the people. From <em>dēmos</em> (people) + <em>kratos</em> (power, rule). Athenian democracy excluded women, slaves, and foreigners — 'the people' was always a partial category.",
    howUsed: "Claimed by nearly every government on earth, including authoritarian ones. 'Democratic People's Republic' appears in the names of single-party states. In American use, contested between majoritarian and constitutional definitions — whether democracy means majority rule or protection of minority rights." },

  { word: "Deserve", category: "Community & Culture",
    definition: "Merit-based, luck-based, or morally determined — not agreed upon",
    phonetic: "di·zurv",
    origin: "Old French <em>deservir</em> — to merit. From Latin <em>deservire</em> — to serve zealously. Originally meant to earn through service — you deserved something by actively earning it. The passive sense (deserving by virtue of who you are) came later.",
    howUsed: "One of the most morally loaded words in the language. 'They don't deserve it' is used to deny aid, rights, and compassion. Underpins debates about welfare, punishment, and wealth — whether outcomes reflect merit or circumstance." },

  { word: "Dignity", category: "Community & Culture",
    definition: "Inherent or earned — the oldest human argument",
    phonetic: "dig·ni·tee",
    origin: "Latin <em>dignitas</em> — worth, merit, prestige. From <em>dignus</em> — worthy. In Roman use, dignity was earned through rank and conduct — it was a social status, not an inherent quality. The idea of inherent human dignity came much later.",
    howUsed: "Human dignity as an inherent, inalienable quality entered Western legal thinking through Enlightenment philosophy and was enshrined in the UN Declaration of Human Rights in 1948. Still contested — whether dignity is something you have or something that must be accorded." },

  { word: "Education", category: "Knowledge & Learning",
    definition: "Learning, credentialing, indoctrination, or liberation — depends on who controls it",
    phonetic: "ej·oo·kay·shən",
    origin: "Latin <em>educatio</em> — a rearing, training. From <em>educare</em> — to bring up, rear. Related to <em>educere</em> — to lead out. The two roots suggest different models: filling (bringing up) versus drawing out what is already there.",
    howUsed: "The tension between those two etymological models — deposit vs. liberation — runs through every education debate. Paulo Freire named it explicitly in 1968. Who controls curriculum controls what counts as educated — this is why education is always a political battleground." },

  { word: "Elite", category: "Power & Politics",
    definition: "Meritocracy's winners or an unaccountable class — depends who's talking",
    phonetic: "i·leet",
    origin: "French <em>élite</em> — choice, selected. From Old French <em>eslite</em> — chosen. From Latin <em>eligere</em> — to choose, select. Originally a neutral term for the chosen or selected — without the resentment the word now carries.",
    howUsed: "Became a pejorative in populist politics of the 20th and 21st centuries. 'Elite' now implies unearned privilege and disconnection from ordinary life — deployed against academics, media figures, and politicians regardless of actual wealth or power." },

  { word: "Evidence", category: "Knowledge & Learning",
    definition: "Proof to some, inconvenience to others",
    phonetic: "ev·i·dəns",
    origin: "Latin <em>evidentia</em> — clearness, distinctness. From <em>evidens</em> — clear, obvious. From <em>ex-</em> (out) + <em>videre</em> (to see). Originally meant something so clear it could be seen directly — not something that required interpretation.",
    howUsed: "The gap between its Latin origin (obvious to sight) and its current use (something requiring evaluation) is the gap that gets exploited. 'Show me the evidence' can mean a genuine request for proof or a rhetorical device to dismiss what is already well established." },

  { word: "Evil", category: "Community & Culture",
    definition: "Theological category, political label, or description of harm",
    phonetic: "ee·vəl",
    origin: "Old English <em>yfel</em> — bad, vicious, ill. One of the oldest words in the Germanic languages. Proto-Germanic root possibly meaning 'exceeding due limits.' The theological sense of evil as an active force or entity developed through Christian doctrine.",
    howUsed: "Political use of 'evil' — 'axis of evil,' 'evil empire' — borrows the theological charge to make political opponents into moral absolutes. The word forecloses negotiation; you cannot compromise with evil. Its use in political speech is therefore almost always a signal that nuance is unwelcome." },

  { word: "Expert", category: "Knowledge & Learning",
    definition: "Trusted authority or unelected elite, depending on whether you like the answer",
    phonetic: "ek·spurt",
    origin: "Latin <em>expertus</em> — tried, proved, known by experience. From <em>experiri</em> — to try, test. Related to <em>experience</em> and <em>experiment</em>. Originally someone who had been tested — knowledge earned through trial, not certification.",
    howUsed: "Authority based on expertise was broadly respected through much of the 20th century. Populist politics of the 21st century attacked expert authority as elitist and undemocratic. Michael Gove's 2016 claim that 'people in this country have had enough of experts' marked a turning point in how the word is used." },

  { word: "Fact", category: "Knowledge & Learning",
    definition: "Observed, agreed upon, or declared — the word claims more certainty than it delivers",
    phonetic: "fakt",
    origin: "Latin <em>factum</em> — a thing done, a deed. From <em>facere</em> — to do, make. Originally meant an act or deed — something that had been done. The sense of 'something known to be true' developed gradually through the 16th and 17th centuries.",
    howUsed: "The phrase 'alternative facts' entered the language in 2017 and crystallized a long-building crisis: the word 'fact' was already doing more work than it could hold. The move from 'fact' to 'factual claim' to 'my facts' traces the collapse of shared epistemic ground." },

  { word: "Fair", category: "Community & Culture",
    definition: "Equal, equitable, or whatever I think it is",
    phonetic: "fair",
    origin: "Old English <em>fæger</em> — beautiful, pleasant. Separately, Old English <em>fæger</em> also meant fitting, proper. The two senses — aesthetic and ethical — ran in parallel for centuries before the ethical meaning dominated.",
    howUsed: "Among the most contested words in politics because it contains two irreconcilable definitions: equal treatment (same rules for everyone) versus equitable treatment (different rules to produce equal outcomes). 'That's not fair' is a primal complaint; what it means is never obvious." },

  { word: "Faith", category: "Further",
    definition: "Trust, religion, or the decision to believe without proof",
    phonetic: "fayth",
    origin: "Latin <em>fides</em> — trust, confidence, reliance. Related to <em>fidere</em> — to trust. Root of <em>fidelity</em>, <em>fiduciary</em>, <em>confide</em>. Originally about trust in a person or promise before it became attached specifically to religious belief.",
    howUsed: "The narrowing of 'faith' to mean specifically religious belief happened gradually. 'Faith community,' 'faith-based' — these are modern coinages. The original Latin sense survives in legal and financial language: fiduciary duty, bona fide, confident." },

  { word: "Family", category: "Origins",
    definition: "Blood, choice, or the unit the state prefers you to be",
    phonetic: "fam·uh·lee",
    origin: "Latin <em>familia</em> — household, including servants and slaves. From <em>famulus</em> — servant. The Roman <em>familia</em> was an economic and legal unit under the authority of the <em>paterfamilias</em> — not primarily a unit of affection.",
    howUsed: "'Family values' became a political phrase in the 1970s and 80s — a shorthand for a specific social conservative vision. 'Chosen family' emerged as a counter-claim. The word is fought over because it carries legal rights, tax implications, and moral authority simultaneously." },

  { word: "Freedom", category: "Power & Politics",
    definition: "Means liberation to one person, license to another, absence of government to a third",
    phonetic: "free·dəm",
    origin: "Old English <em>frēodōm</em> — power of self-determination. From <em>frēo</em> (free) + <em>dōm</em> (judgment, condition). The Proto-Germanic root is related to 'love' — the free person was one who belonged to the beloved community, not to a master.",
    howUsed: "The most contested word in American political life. Liberty and freedom are often used interchangeably but carry different weights — freedom tends toward the personal and emotional, liberty toward the legal and civic. 'Freedom' has been invoked to justify both abolition and slavery, both protest and suppression." },

  { word: "Future", category: "Not Classified",
    definition: "Promise, threat, or abstraction used to defer present action",
    phonetic: "fyoo·chər",
    origin: "Latin <em>futurus</em> — about to be, going to be. Future participle of <em>esse</em> — to be. Grammatically, the future is just the 'being' that hasn't happened yet. The word entered English in the 14th century.",
    howUsed: "Used politically to defer present action — 'for future generations' licenses sacrifice now for benefits that may never arrive. Also used to make present decisions feel inevitable: 'the future is X' implies resistance is futile. Both moves are worth watching for." },

  { word: "Gender", category: "Origins",
    definition: "Biology, identity, performance, or spectrum — the conversation is ongoing",
    phonetic: "jen·dər",
    origin: "Latin <em>genus</em> — kind, type, birth. Related to <em>generare</em> — to generate. In grammar, gender referred to noun categories — masculine, feminine, neuter — not to human biology. The word's application to human identity is relatively recent.",
    howUsed: "Sex and gender were used interchangeably until the 1950s-60s when researchers began distinguishing biological sex from social identity. That distinction is now the fault line of one of the most intense political conflicts of the 21st century — a debate that is ultimately about who has the authority to define categories." },

  { word: "God", category: "Further",
    definition: "Creator, metaphor, authority, or comfort — the most loaded word in any language",
    phonetic: "god",
    origin: "Proto-Germanic <em>*guthan</em> — that which is invoked, or possibly that which is poured as a libation. Among the oldest words in any Germanic language. The capitalized singular God — the monotheistic deity — is a usage specific to the Abrahamic traditions.",
    howUsed: "Invoked in American political life with unusual frequency for a secular democracy. 'One nation under God' was added to the Pledge of Allegiance in 1954. 'In God We Trust' became the national motto the same decade — both additions were Cold War moves, distinguishing America from godless communism." },

  { word: "Good", category: "Community & Culture",
    definition: "Moral, effective, or just pleasant — the word carries all three",
    phonetic: "good",
    origin: "Old English <em>gōd</em> — virtuous, desirable, fitting. Proto-Germanic root. Separate from the word for God — a common misconception. Related to the German <em>gut</em> and Dutch <em>goed</em>.",
    howUsed: "Carries moral, functional, and aesthetic meanings simultaneously — 'a good person,' 'a good tool,' 'a good painting' use the same word for different things. The conflation is rarely noticed but shapes how moral arguments are made: things that work are assumed to be right." },

  { word: "Government", category: "Power & Politics",
    definition: "Servant of the people or threat to liberty — same institution, opposite readings",
    phonetic: "guv·ərn·mənt",
    origin: "Latin <em>gubernare</em> — to steer, to pilot a ship. From Greek <em>kybernan</em> — same meaning. The governing metaphor was always navigation — finding a course through unpredictable conditions. <em>Cybernetics</em> and <em>governor</em> share the same root.",
    howUsed: "In American political culture, 'government' became a term of suspicion in the late 20th century. Reagan's 1981 claim that 'government is not the solution; government is the problem' crystallized an anti-government politics that has since shaped policy for decades." },

  { word: "Growth", category: "Power & Politics",
    definition: "Economic progress or ecological destruction — depends on the time horizon",
    phonetic: "grohth",
    origin: "Old Norse <em>grōthr</em> — growth. From Proto-Germanic roots related to growing, greening. Originally biological — plants growing — before becoming the primary metric of economic health in the 20th century.",
    howUsed: "GDP growth became the dominant measure of national success after World War II. Critics argue this conflates economic activity with wellbeing — a growing economy can coexist with falling life expectancy, rising inequality, and environmental destruction. Alternative metrics (happiness index, human development index) challenge the growth assumption." },

  { word: "Health", category: "Myself & I",
    definition: "Physical state, industry, or human right — not settled",
    phonetic: "helth",
    origin: "Old English <em>hælth</em> — wholeness, a being whole. From <em>hāl</em> — whole, uninjured. Related to <em>whole</em>, <em>heal</em>, and <em>holy</em> — all from the same root. Health was originally about wholeness, not just the absence of disease.",
    howUsed: "The WHO's 1948 definition — 'a state of complete physical, mental and social well-being' — was radical in its scope. In American political life, health is debated primarily as a market commodity or as a government program. The original sense of wholeness rarely enters the policy conversation." },

  { word: "Heritage", category: "Origins",
    definition: "Pride, mythology, or unexamined inheritance",
    phonetic: "her·i·tij",
    origin: "Old French <em>heritage</em> — inheritance, legacy. From <em>heriter</em> — to inherit. From Latin <em>heres</em> — heir. Originally strictly legal — what you were entitled to inherit — before becoming cultural and emotional.",
    howUsed: "'Heritage' carries a soft glow that 'history' doesn't — it implies something worth preserving, something to be proud of. 'Heritage sites,' 'heritage language,' 'Southern heritage' — each use involves a claim about what deserves to be passed forward, and what does not." },

  { word: "History", category: "Not Classified",
    definition: "What happened, what was recorded, or what was decided mattered",
    phonetic: "his·tə·ree",
    origin: "Greek <em>historia</em> — inquiry, knowledge obtained by inquiry. From <em>histor</em> — knowing, learned. Herodotus used it to describe his method — asking questions, gathering accounts. Originally a process, not a body of content.",
    howUsed: "'History is written by the winners' is the folk wisdom that captures the word's political dimension. Curriculum battles over what history gets taught are battles over national identity. 'We're on the right side of history' borrows the word's authority to claim future vindication." },

  { word: "Home", category: "Myself & I",
    definition: "Place, feeling, nation, or the thing you can lose",
    phonetic: "hohm",
    origin: "Old English <em>hām</em> — village, estate, dwelling place. Proto-Germanic root. Originally referred to a settled place and community — closer to 'homeland' than 'house.' The intimate, interior sense of home as sanctuary developed later.",
    howUsed: "Home carries enormous emotional and legal weight — property rights, privacy protections, family law all pivot on it. 'Homeland' was a relatively unused word in American English until 2001, when the Department of Homeland Security gave it a new and specific charge." },

  { word: "Immigrant", category: "Origins",
    definition: "Neighbor, threat, or economic category — depends on the decade",
    phonetic: "im·i·grənt",
    origin: "Latin <em>immigrare</em> — to move into. From <em>in-</em> (into) + <em>migrare</em> (to move). The word distinguishes the direction of movement — immigration is into a place, emigration is out of one. Neutral in origin; politically charged in use.",
    howUsed: "The word choice matters: 'immigrant,' 'migrant,' 'undocumented immigrant,' 'illegal alien,' 'newcomer' — each frames the same person differently and implies different policy responses. The shift from 'illegal alien' (a legal category) to 'undocumented immigrant' (a status description) was itself a political act." },

  { word: "Investment", category: "Power & Politics",
    definition: "Building something or extracting value — both use the same word",
    phonetic: "in·vest·mənt",
    origin: "Medieval Latin <em>investire</em> — to clothe, to surround. From <em>in-</em> + <em>vestire</em> — to dress. Originally meant to clothe someone in the robes of an office — to invest with authority. The financial sense developed from the idea of committing resources to a purpose.",
    howUsed: "Government spending on education, healthcare, and infrastructure is called 'investment' by supporters and 'spending' by critics — same allocation, opposite framings. The word launders expenditure by implying return. 'Invest in your future' is used to sell everything from college tuition to lottery tickets." },

  { word: "Judgment", category: "Community & Culture",
    definition: "Divine reckoning, personal criticism, or legal ruling",
    phonetic: "juj·mənt",
    origin: "Old French <em>jugement</em> — legal decision. From Latin <em>judicare</em> — to judge, from <em>jus</em> (law, right) + <em>dicere</em> (to say). Originally strictly legal — a formal pronouncement — before expanding to mean any evaluative opinion.",
    howUsed: "'Don't judge' became a cultural injunction in the late 20th century — a democratizing of moral authority that also evacuated the concept of content. The religious sense (Last Judgment, divine reckoning) persists alongside the casual social sense." },

  { word: "Justice", category: "Power & Politics",
    definition: "Punishment, restoration, or equity — three entirely different systems",
    phonetic: "jus·tis",
    origin: "Latin <em>justitia</em> — righteousness, equity. From <em>justus</em> — just, righteous. From <em>jus</em> — law, right. Justice and law were not synonyms in Latin — justice was the principle, law was the instrument. The gap between them is still the central problem of jurisprudence.",
    howUsed: "Three competing systems all use the word: retributive justice (punishment), restorative justice (repair), distributive justice (fairness of outcomes). Criminal justice, social justice, and economic justice describe different problems with the same word — and policy debates are often really disputes about which definition applies." },

  { word: "Law", category: "Power & Politics",
    definition: "Protection or weapon, depending entirely on where you're standing",
    phonetic: "law",
    origin: "Old Norse <em>lagu</em> — something laid down or fixed. From Proto-Germanic <em>*lagam</em> — to lay. Law was literally that which was laid down — settled, fixed, established. Related to <em>lie</em> and <em>lay</em> in English.",
    howUsed: "Rule of law implies law as neutral arbiter above power. Critical legal studies argues law is always an expression of power — who wrote it, who enforces it, and whose behavior it regulates tells the story. Both observations are true simultaneously." },

  { word: "Legacy", category: "Not Classified",
    definition: "What you leave or what you're blamed for",
    phonetic: "leg·ə·see",
    origin: "Medieval Latin <em>legatia</em> — office of a legate, then bequest. From <em>legare</em> — to send as a deputy, to bequeath. Originally strictly about property left at death. The broader sense — what one leaves behind in terms of influence or reputation — is a modern extension.",
    howUsed: "Politicians, athletes, and executives are evaluated constantly on their 'legacy' — an accounting that happens before and after death. The word implies that actions will be judged by a future that may have different values. 'Legacy admission' to universities repurposes the word to describe inherited privilege." },

  { word: "Liberty", category: "Power & Politics",
    definition: "Often used as freedom's more formal twin — with very different implications",
    phonetic: "lib·ər·tee",
    origin: "Latin <em>libertas</em> — freedom, the condition of a free person. From <em>liber</em> — free. In Roman law, a specific legal status — the opposite of slavery. The Statue of Liberty, the Liberty Bell — the word carries a formal, civic weight that 'freedom' does not always.",
    howUsed: "In American political philosophy, liberty tends toward the negative — freedom from interference, especially from government. The word has been claimed most insistently by libertarian and conservative movements. 'Civil liberties' is a different usage — specific protections against state power." },

  { word: "Life", category: "Myself & I",
    definition: "Biological, biographical, or the political category in 'pro-life'",
    phonetic: "līf",
    origin: "Old English <em>lif</em> — existence, way of living. Proto-Germanic root. Among the oldest words in the language. Biologically, legally, and philosophically contested at both ends — when it begins and when it ends.",
    howUsed: "'Pro-life' as a political label emerged in the 1970s, appropriating the word's broadest possible meaning for a specific legislative agenda. The claim that opposing abortion is 'pro-life' while other life-related policies are not was noted early and has been contested ever since." },

  { word: "Memory", category: "Not Classified",
    definition: "Individual, collective, or politically managed",
    phonetic: "mem·ə·ree",
    origin: "Latin <em>memoria</em> — remembrance. From <em>memor</em> — mindful. Related to <em>mourn</em> — both from Proto-Indo-European roots meaning to be anxious, to care about. Memory and grief were linguistically adjacent from the beginning.",
    howUsed: "Individual memory is unreliable in ways now well documented by psychology. Collective memory — what a culture chooses to remember — is shaped by power. Monuments, holidays, and textbooks are memory management systems. 'Never forget' is an instruction to override forgetting that would otherwise occur naturally." },

  { word: "Minority", category: "Origins",
    definition: "Numerical or structural — not the same thing",
    phonetic: "mi·nor·i·tee",
    origin: "Latin <em>minoritas</em> — lesser number. From <em>minor</em> — smaller, lesser. Originally strictly mathematical — the smaller of two quantities. Applied to people and groups, the word carries the mathematical sense but also implies reduced power and rights.",
    howUsed: "Numerical minority and structural minority are not the same — women are a numerical majority in most societies but have historically held minority power. 'Minority rights' in constitutional law protects the smaller group from the larger; 'minority community' in social usage refers to groups marginalized by race, ethnicity, or identity." },

  { word: "Miracle", category: "Further",
    definition: "Divine intervention or improbable event — language reveals belief",
    phonetic: "mir·i·kəl",
    origin: "Latin <em>miraculum</em> — object of wonder. From <em>mirari</em> — to wonder at. Related to <em>mirror</em> — both from seeing something astonishing. Originally a neutral word for something wonderful before narrowing to mean specifically divine intervention.",
    howUsed: "Retained religious meaning while also acquiring secular uses — 'economic miracle,' 'medical miracle.' The secular uses borrow the emotional charge of divine intervention without the theological commitment. Whether the gap between the two uses matters is exactly the question the word raises." },

  { word: "Misinformation", category: "Knowledge & Learning",
    definition: "False content — or content someone in power doesn't want believed",
    phonetic: "mis·in·fər·may·shən",
    origin: "From <em>mis-</em> (wrongly) + <em>information</em>. The prefix <em>mis-</em> is from Old English, implying wrongness or error. Distinct from <em>disinformation</em> (deliberately false) and <em>malinformation</em> (true but used harmfully) — a distinction rarely made in public debate.",
    howUsed: "The word gained enormous political currency in the 2010s as social media amplified false content. Its use became contested when the same label was applied to heterodox scientific claims later proven correct, suppressed political speech, and genuinely false propaganda — without distinguishing between them." },

  { word: "Modern", category: "Not Classified",
    definition: "Current, Western, or superior — the assumptions are buried in the word",
    phonetic: "mod·ərn",
    origin: "Late Latin <em>modernus</em> — of the present time. From <em>modo</em> — just now, recently. The word is only about recency — modern means now. Its association with progress, Western development, and superiority to the past are cultural assumptions layered on top.",
    howUsed: "'Modernization' became development policy language in the mid-20th century — implying a single path from traditional to modern that all societies should follow. Critics noted this path looked remarkably like the Western industrialized one. The word still carries assumptions about whose present counts as the standard." },

  { word: "Narrative", category: "Knowledge & Learning",
    definition: "Story, spin, or the frame around the facts",
    phonetic: "nar·ə·tiv",
    origin: "Latin <em>narrare</em> — to tell, relate. From <em>gnarus</em> — knowing. Related to <em>knowledge</em> — narrative was always tied to knowing and telling. Entered political and media language heavily in the late 20th century.",
    howUsed: "'Controlling the narrative' entered political language as a substitute for 'controlling the story' — but 'narrative' carries more intellectual weight, implying a constructed frame rather than merely a sequence of events. Widely used and widely distrusted — 'that's just a narrative' is now a dismissal." },

  { word: "Nation", category: "Origins",
    definition: "Geography, people, government, or myth — not always the same thing",
    phonetic: "nay·shən",
    origin: "Latin <em>natio</em> — birth, origin, race of people. From <em>nasci</em> — to be born. Originally meant a people united by birth or origin — ethnic rather than political. The idea of a nation as a political-territorial unit came much later, emerging strongly in the 19th century.",
    howUsed: "Nation and state are often conflated but were designed to solve different problems. A state is a political-legal entity; a nation is a cultural-ethnic identity. Nation-states — where the two align — are the 20th century norm but were never universal. Nationalism is the political doctrine that they should align." },

  { word: "Native", category: "Origins",
    definition: "Indigenous or simply born here — two very different claims",
    phonetic: "nay·tiv",
    origin: "Latin <em>nativus</em> — innate, natural, from birth. From <em>nasci</em> — to be born. Related to <em>nation</em> and <em>nature</em>. The same root — being born — generates all three words. Who counts as native depends entirely on where you start the clock.",
    howUsed: "'Native American' as a term replaced 'Indian' in official usage in the latter 20th century — a shift in naming that carried political weight. 'Going native' was a colonial phrase for assimilation into local culture, invariably pejorative. The word's authority rests entirely on how far back 'native' is taken." },

  { word: "Natural", category: "Community & Culture",
    definition: "From nature or morally correct — the conflation is deliberate",
    phonetic: "nach·ər·əl",
    origin: "Latin <em>naturalis</em> — by birth, according to nature. From <em>natura</em> — nature, character, essence. From <em>nasci</em> — to be born. Natural, nation, and native all share the birth root — what is natural is what was there at birth.",
    howUsed: "'Natural' is among the most powerful rhetorical moves in moral argument — if something is natural, it appears beyond human choice or criticism. 'Unnatural' works the same way in reverse. The fallacy of moving from 'is natural' to 'is good' — the naturalistic fallacy — was identified by philosophers but thrives in everyday argument." },

  { word: "News", category: "Knowledge & Learning",
    definition: "Events reported, events selected, or events manufactured",
    phonetic: "nyooz",
    origin: "Middle English <em>newes</em> — new things, tidings. Plural of <em>new</em>. The word is simply the plural of new — news was originally just new things. The institutional machinery of journalism is entirely absent from the etymology.",
    howUsed: "The business model of news has shaped its content at every stage — town crier, penny press, broadcast, cable, social media. 'Fake news' as a phrase was coined to describe fabricated content and then repurposed by politicians to describe unfavorable coverage, draining it of specific meaning." },

  { word: "Normal", category: "Origins",
    definition: "Statistical average or social enforcement",
    phonetic: "nor·məl",
    origin: "Latin <em>normalis</em> — made according to a carpenter's square. From <em>norma</em> — carpenter's square, rule, pattern. Originally a technical term meaning 'at right angles' — perfectly perpendicular — before becoming a social category.",
    howUsed: "The shift from 'normal' as statistical average to 'normal' as social standard is the shift that does the most work. 'That's not normal' can mean it's rare (descriptive) or it's unacceptable (prescriptive). The two meanings are conflated constantly, most harmfully in medical and psychological contexts." },

  { word: "Opinion", category: "Knowledge & Learning",
    definition: "Personal view or the equal of established fact — being treated as the same is the problem",
    phonetic: "ə·pin·yən",
    origin: "Latin <em>opinio</em> — belief, conjecture, reputation. From <em>opinari</em> — to think, believe. Always carried a sense of uncertainty — an opinion was a belief held without certainty, distinct from knowledge. The distinction has largely collapsed in common use.",
    howUsed: "'That's just your opinion' is used to dismiss established findings — a move that exploits the original sense (uncertain belief) to undermine what is actually well-evidenced. The phrase 'in my opinion' disclaims responsibility for a claim rather than honestly flagging uncertainty." },

  { word: "Order", category: "Power & Politics",
    definition: "Peace or enforcement — whose order matters enormously",
    phonetic: "or·dər",
    origin: "Latin <em>ordo</em> — row, arrangement, rank. From Proto-Indo-European roots meaning to put in order. Military rank, religious orders, social hierarchy, and the injunction to 'restore order' all descend from the same root: arrangement by rank.",
    howUsed: "'Law and order' as a political phrase dates to the Nixon era and has been reliably deployed since to signal tough-on-crime politics. 'Order' implies there was order before, that disorder is an intrusion, and that restoration is the goal — all contestable assumptions." },

  { word: "Patriot", category: "Power & Politics",
    definition: "Lover of country or enforcer of conformity",
    phonetic: "pay·tree·ət",
    origin: "Greek <em>patriōtēs</em> — fellow-countryman. From <em>patrios</em> — of one's fathers, ancestral. From <em>patēr</em> — father. Originally meant a fellow citizen or compatriot — without the specific devotion implied today. Patriotism as an actively celebrated virtue is relatively modern.",
    howUsed: "The word has been weaponized to mean political conformity. 'Patriot Act,' 'Patriot' as a name for militias, far-right media outlets, and political parties — all claim ownership of love of country as a way of questioning others' loyalty. Ambrose Bierce defined it in 1906 as 'combustible rubbish ready to the torch of any one ambitious to illuminate his name.'" },

  { word: "Populism", category: "Power & Politics",
    definition: "The people's voice or mob rule dressed up in a flag",
    phonetic: "pop·yoo·liz·əm",
    origin: "Latin <em>populus</em> — the people. The American Populist Party emerged in the 1890s as a farmers' movement against railroad monopolies and financial elites — a specific left-wing movement with specific economic demands. The generic use of 'populism' as a style came later.",
    howUsed: "Populism now describes both left and right political movements that claim to represent 'the people' against 'the elite' — so broad it has nearly lost descriptive power. Academics debate whether populism is a thin ideology, a political style, or a rhetorical strategy. The one constant: its definition of 'the people' always excludes someone." },

  { word: "Poverty", category: "Power & Politics",
    definition: "Circumstance, system, or personal failure — the diagnosis determines the cure",
    phonetic: "pov·ər·tee",
    origin: "Old French <em>poverté</em>. Latin <em>paupertas</em> — smallness of means. From <em>pauper</em> — poor. The Latin root implied not destitution but insufficiency — having less than required. The threshold of poverty is always defined relative to something.",
    howUsed: "The U.S. poverty line was established in 1963 based on food costs — a methodology widely criticized as outdated. Whether poverty is understood as a personal failing, a structural condition, or a policy choice determines what solutions are considered. The framing precedes the number." },

  { word: "Power", category: "Power & Politics",
    definition: "Authority, force, or energy — and who has it changes everything",
    phonetic: "pow·ər",
    origin: "Old French <em>pooir</em> — to be able. From Latin <em>potere</em> — to be able. Related to <em>potent</em>, <em>possible</em>, <em>potency</em>. Power in its root is simply capacity — ability to do. The coercive dimension — power over — is an elaboration.",
    howUsed: "Political science distinguishes hard power (military, economic coercion) from soft power (cultural influence, attraction). Michel Foucault's analysis of power as diffuse, productive, and operating through norms rather than commands challenged the state-centered view. 'Speaking truth to power' assumes they are opposites; Foucault would question that." },

  { word: "Prayer", category: "Further",
    definition: "Communication with the divine or wishful thinking — depends entirely on belief",
    phonetic: "prair",
    origin: "Old French <em>preiere</em>. Latin <em>precaria</em> — obtained by entreaty. From <em>precari</em> — to entreat, pray. Related to <em>precarious</em> — both come from asking for something you have no right to demand. Prayer is etymologically an uncertain request.",
    howUsed: "'Thoughts and prayers' became a phrase of critique after mass shootings — shorthand for performed empathy without policy action. The phrase exposed the gap between the religious meaning (sincere petition to the divine) and its political deployment (public statement of sympathy)." },

  { word: "Privilege", category: "Origins",
    definition: "Advantage, blessing, or grievance depending on the conversation",
    phonetic: "priv·uh·lij",
    origin: "Latin <em>privilegium</em> — a law applying to one person. From <em>privus</em> (private, individual) + <em>lex/legis</em> (law). Originally meant a special legal advantage — a specific law written for one person. The modern sense of unearned social advantage came through academic sociology in the late 20th century.",
    howUsed: "Peggy McIntosh's 1989 essay 'White Privilege: Unpacking the Invisible Knapsack' introduced the term to mainstream discourse. It then became one of the most contested words in American culture — simultaneously a sociological tool and a political flashpoint. Those who reject it most often conflate structural advantage with personal accusation." },

  { word: "Progress", category: "Not Classified",
    definition: "Forward movement or destruction of what works — both claims made sincerely",
    phonetic: "prog·res",
    origin: "Latin <em>progressus</em> — a going forward. From <em>progredi</em> — to go forward. From <em>pro-</em> (forward) + <em>gradi</em> (to step). The idea that forward motion is inherently good — that history moves in a direction and that direction is improvement — was not assumed before the Enlightenment.",
    howUsed: "The progressive/conservative divide is largely a dispute about whether change is improvement. 'Progressive' as a political self-description claims the word's positive charge; conservatives argue that not all forward movement is good. Both are using 'progress' to mean something more than just 'change.'" },

  { word: "Propaganda", category: "Knowledge & Learning",
    definition: "Enemy messaging — your side calls it communication",
    phonetic: "prop·ə·gan·də",
    origin: "Latin <em>Congregatio de Propaganda Fide</em> — the Congregation for Propagating the Faith, established by Pope Gregory XV in 1622. Originally meant the spreading of Catholic doctrine. Secular and pejorative uses developed during and after World War I.",
    howUsed: "Almost always attributed to opponents. 'That's propaganda' functions as a dismissal — but the word originally just meant organized persuasion, not necessarily false persuasion. All advertising, all political communication, and all education involve organized persuasion. The question is always: whose?" },

  { word: "Protest", category: "History & Civilization",
    definition: "Democratic expression or public disorder — same event, different headlines",
    phonetic: "proh·test",
    origin: "Latin <em>protestari</em> — to declare publicly. From <em>pro-</em> (before, publicly) + <em>testari</em> (to witness, testify). Originally a formal legal declaration — a public testament. The sense of opposition or objection came later.",
    howUsed: "The same event — people in streets challenging authority — is called a protest by sympathizers and a riot by opponents. Coverage studies consistently show the word choice tracks political alignment. The right to protest is constitutionally protected; the description of what counts as a protest is not." },

  { word: "Race", category: "Origins",
    definition: "Biological fiction, social reality, and lived experience — all three at once",
    phonetic: "rays",
    origin: "Old French <em>rasse</em>, Italian <em>razza</em> — group, kind, lineage. Etymology disputed — possibly from Arabic <em>ras</em> (head, origin) or Latin <em>ratio</em> (kind). Appeared in European languages in the 15th-16th centuries as Atlantic trade and colonialism created demand for a vocabulary of human difference.",
    howUsed: "The scientific consensus is that race is a social construct without meaningful biological basis — genetic variation within so-called racial groups exceeds variation between them. This does not make race unreal; as a social reality with legal, economic, and lived consequences, it is very real. The distinction between biological fiction and social fact is itself the whole argument." },

  { word: "Reform", category: "Power & Politics",
    definition: "Progress or erosion, depending on what you're attached to",
    phonetic: "ri·form",
    origin: "Latin <em>reformare</em> — to form again, reshape. From <em>re-</em> (again) + <em>formare</em> (to form). Originally meant to restore a previous good form — to correct something that had gone wrong. The progressive sense of reform as improvement toward something new came later.",
    howUsed: "Reform is always someone's gain and someone's loss, but the word obscures this. 'Criminal justice reform,' 'tax reform,' 'immigration reform' — each phrase implies improvement without specifying direction. Who uses the word and who fears it are telling." },

  { word: "Religion", category: "Further",
    definition: "An organized system of belief, practice, and community — present in every layer of human history, still shaping the present.",
    phonetic: "ri·lij·ən",
    origin: "Latin <em>religio</em> — obligation, bond, reverence. Etymology disputed: possibly from <em>religare</em> (to bind again) or <em>relegere</em> (to re-read, to go over again). The binding sense and the careful observation sense both fit — religion as both obligation and practice.",
    howUsed: "The category of 'religion' as distinct from politics, law, and science is itself a modern Western construction. Many traditions do not separate sacred from secular in ways the word assumes. 'Religious freedom' in American law requires defining what counts as religion — an ongoing legal and political negotiation." },

  { word: "Responsibility", category: "Community & Culture",
    definition: "Personal accountability or systemic obligation — the debate is which one applies",
    phonetic: "ri·spon·si·bil·i·tee",
    origin: "Latin <em>respondere</em> — to answer, to respond. From <em>re-</em> (back) + <em>spondere</em> (to pledge). To be responsible was originally to be answerable — to have an obligation to give an account. The moral weight came through the legal sense.",
    howUsed: "Personal responsibility and systemic responsibility are the two poles of most social policy debates. 'Take responsibility' addressed to an individual; 'systemic responsibility' pointed at institutions. Which frame applies determines what counts as a solution." },

  { word: "Revolution", category: "History & Civilization",
    definition: "Heroic founding or dangerous chaos, depending on whose side won",
    phonetic: "rev·ə·loo·shən",
    origin: "Latin <em>revolutio</em> — a turning around. From <em>revolvere</em> — to roll back. Originally an astronomical term — the revolution of planets, their return. The political sense — a turning over of the existing order — borrowed the astronomical metaphor.",
    howUsed: "Revolutions are named and framed retrospectively by whoever writes the history. The American Revolution is celebrated; other revolutions are called coups or insurrections by those who oppose them. 'Revolutionary' is used to sell both political change and consumer products — often simultaneously." },

  { word: "Rights", category: "Power & Politics",
    definition: "God-given, government-granted, or socially constructed — all three camps exist",
    phonetic: "rīts",
    origin: "Old English <em>riht</em> — just, good, fitting. Related to Latin <em>rectus</em> — straight. Rights were originally what was right — morally correct — before becoming a legal and political category of entitlements.",
    howUsed: "Natural rights, legal rights, and human rights are three different concepts using the same word. Natural rights exist independent of law (Jefferson); legal rights are what the law grants; human rights are international claims. Whether rights are God-given, socially constructed, or legally granted is the entire philosophical dispute." },

  { word: "Riot", category: "History & Civilization",
    definition: "What they call a protest they disapprove of",
    phonetic: "rī·ət",
    origin: "Old French <em>riote</em> — quarrel, dispute. Of uncertain further origin. Originally meant argument or noisy behavior before acquiring the sense of collective violent disorder.",
    howUsed: "Studies of media coverage show 'riot' is applied to the same events differently by different outlets tracking political alignment. The 1992 Los Angeles events are called a riot or an uprising depending on the speaker's politics. The distinction matters legally — riot charges carry penalties that protest does not." },

  { word: "Sacred", category: "Further",
    definition: "Holy, protected, or beyond criticism",
    phonetic: "say·krid",
    origin: "Latin <em>sacer</em> — holy, set apart, dedicated to a god. From Proto-Indo-European root meaning to sanctify. Related to <em>sacrifice</em> — to make sacred by giving up. The sacred was originally that which was set apart from ordinary use.",
    howUsed: "Sacred has migrated from religious to secular use — 'sacred institution,' 'sacred duty,' 'nothing is sacred.' The secular uses borrow the absoluteness of the religious sense — sacred things cannot be questioned or touched — to place certain subjects beyond criticism." },

  { word: "Salvation", category: "Further",
    definition: "Religious rescue or political promise — used by both",
    phonetic: "sal·vay·shən",
    origin: "Latin <em>salvatio</em> — rescue, deliverance. From <em>salvare</em> — to save. Related to <em>salve</em> and <em>safe</em>. Originally theological — rescue from sin and its consequences — before migrating to secular promise.",
    howUsed: "Political movements regularly appropriate the emotional charge of salvation — rescue from existential threat, from corruption, from decline. The messianic register in political speech borrows directly from religious tradition. 'He alone can fix it' is salvation language applied to a candidate." },

  { word: "Science", category: "Knowledge & Learning",
    definition: "Method, institution, consensus, or authority — critics conflate them deliberately",
    phonetic: "sī·əns",
    origin: "Latin <em>scientia</em> — knowledge, from <em>scire</em> — to know. Originally meant knowledge in general — any organized body of understanding. The specific meaning of systematic empirical investigation developed through the Scientific Revolution of the 16th-17th centuries.",
    howUsed: "'Follow the science' and 'the science isn't settled' are both moves that exploit the word's authority. Science is a method, not a set of conclusions — conclusions change as evidence accumulates. Critics of science often conflate the method (reliable) with specific applications or institutions (fallible)." },

  { word: "Security", category: "Power & Politics",
    definition: "Safety or control — both use the same infrastructure",
    phonetic: "si·kyoor·i·tee",
    origin: "Latin <em>securitas</em> — freedom from care. From <em>se-</em> (without) + <em>cura</em> (care, worry). Security was originally about freedom from anxiety — a psychological state. The physical and political senses of protection from external threat came later.",
    howUsed: "After 9/11, 'security' became the organizing word of American domestic policy — Homeland Security, Transportation Security Administration, security theater. The word's authority is hard to challenge: to oppose security measures is to accept insecurity. This rhetorical structure has been noted and criticized across the political spectrum." },

  { word: "Shame", category: "Community & Culture",
    definition: "Moral corrective or social weapon",
    phonetic: "shaym",
    origin: "Old English <em>scamu</em> — shame, confusion, disgrace. Proto-Germanic root. Related to the verb 'to cover' — shame originally involved hiding, covering oneself. The exposure dimension of shame (being seen) and the hiding dimension (wanting to disappear) are both in the etymology.",
    howUsed: "Shame and guilt are related but distinct — guilt is about what you did, shame is about what you are. Psychology has examined shame as both a moral corrective and a source of destructive self-concept. 'Shaming' — public exposure via social media — revived the word's communal enforcement dimension." },

  { word: "Sin", category: "Further",
    definition: "Religious transgression or social failure — still very much in circulation",
    phonetic: "sin",
    origin: "Old English <em>synn</em> — moral wrongdoing, offense against God. Proto-Germanic root. Some scholars connect it to Latin <em>sons, sontis</em> — guilty, the guilty party. The legal and theological senses were adjacent from the beginning.",
    howUsed: "Sin has migrated from theology into secular moral language — 'the sin of omission,' 'cardinal sins of management.' The migration borrows the weight of theological transgression for secular judgments. In political speech, invoking sin signals a moral seriousness beyond policy disagreement." },

  { word: "Socialism", category: "Power & Politics",
    definition: "Collective care or government overreach — rarely defined before being invoked",
    phonetic: "soh·shə·liz·əm",
    origin: "French <em>socialisme</em>, early 19th century. From <em>social</em> + <em>-isme</em>. Emerged as a response to industrial capitalism — the word was coined to describe systems prioritizing collective welfare over individual accumulation. First appeared in print around 1832.",
    howUsed: "In American political discourse, 'socialism' is rarely defined before being invoked — functioning as a threat word rather than a description. Medicare, Social Security, and public libraries are called socialist by critics; European social democracies call themselves capitalist. The word covers everything from Stalinist command economies to Scandinavian welfare states." },

  { word: "Soul", category: "Further",
    definition: "Theological reality, metaphor, or the part of a person that can't be quantified",
    phonetic: "sohl",
    origin: "Old English <em>sāwol</em> — spiritual and emotional part of a person. Proto-Germanic. Among the oldest abstract concepts in the language — evidence of the word predates written English. The soul was the animating principle, the thing that made the body live.",
    howUsed: "Soul has resisted complete secularization — unlike many religious words, it survives in everyday speech as something beyond metaphor: 'I put my soul into it,' 'the soul of the nation.' In political speech, 'the soul of America' invokes something precious and at risk — a rhetorical move that borrows theological weight." },

  { word: "Sovereignty", category: "Power & Politics",
    definition: "National independence or the right of the powerful to do as they please",
    phonetic: "sov·rin·tee",
    origin: "Old French <em>souveraineté</em>. From <em>souverain</em> — supreme, from Latin <em>superanus</em> — above, from <em>super</em>. Sovereignty was the quality of being above — above the law, above challenge, supreme. The modern political concept of state sovereignty derives from the Peace of Westphalia in 1648.",
    howUsed: "Sovereignty is claimed simultaneously by nation-states (territorial sovereignty), indigenous peoples (tribal sovereignty), and individuals (bodily sovereignty). The claims conflict constantly. 'Sovereignty' in trade debates refers to economic self-determination; in immigration debates to border control; in indigenous rights to pre-existing authority." },

  { word: "Tax", category: "Power & Politics",
    definition: "Civic contribution or government theft — one of the oldest fights",
    phonetic: "taks",
    origin: "Latin <em>taxare</em> — to touch sharply, to estimate, to assess. From Proto-Indo-European root meaning to touch. <em>Task</em> and <em>tax</em> share an origin — both involved an assigned obligation, something required of you.",
    howUsed: "The framing war over taxes is one of the oldest in democratic politics. 'Tax relief' (Reagan-era language) frames taxes as a burden to be lifted; 'investment in the commons' frames them as collective contribution. The same transfer carries opposite moral valence depending on the word chosen." },

  { word: "Terrorism", category: "History & Civilization",
    definition: "Political violence by enemies — rarely applied to ourselves",
    phonetic: "ter·ə·riz·əm",
    origin: "French <em>terrorisme</em>. Coined during the French Revolution's Reign of Terror (1793–94) — originally describing state violence against citizens, not non-state violence against states. The meaning inverted over the 19th and 20th centuries.",
    howUsed: "No agreed legal definition exists internationally. The absence is not accidental — states resist defining terrorism in ways that might apply to their own actions. 'One man's terrorist is another man's freedom fighter' became a cliché because it identifies a real problem: the word describes motive and legitimacy, not method." },

  { word: "The Market", category: "Power & Politics",
    definition: "The collective mechanism of economic exchange — spoken of as if it were a person with opinions, feelings, and the right to decide",
    phonetic: "thə mar·kit",
    origin: "Latin <em>mercatus</em> — trade, traffic. From <em>merx/mercis</em> — goods, merchandise. Related to <em>Mercury</em> — god of commerce, travel, and communication. 'The market' as an autonomous agent — 'the market decided,' 'the market punished' — is a modern metaphor without ancient precedent.",
    howUsed: "Treating the market as a person with preferences and judgments is the defining rhetorical move of neoliberal economics. 'The market' cannot be argued with, voted against, or held accountable — it simply is. This depoliticizes what are actually choices made by people with power and interests." },

  { word: "Theory", category: "Knowledge & Learning",
    definition: "In science: well-tested explanation. In common use: a guess. The gap is exploited constantly",
    phonetic: "theer·ee",
    origin: "Greek <em>theoria</em> — looking at, contemplation, speculation. From <em>theoros</em> — spectator. Related to <em>theater</em> — both involve looking. Originally meant careful observation and contemplation before acquiring its scientific and philosophical meanings.",
    howUsed: "'It's just a theory' exploits the gap between the scientific and everyday meanings. In science, a theory is an explanation supported by extensive evidence — evolution, gravity, germ theory. In common use, theory means a guess. The gap is exploited systematically to undermine scientific consensus." },

  { word: "They", category: "Origins",
    definition: "The most dangerous three-letter word",
    phonetic: "thay",
    origin: "Old Norse <em>þeir</em> — they. Replaced the Old English third-person plural pronoun in the 13th-14th centuries. The singular 'they' — used when gender is unknown or unspecified — has been documented in English since at least the 14th century, appearing in Chaucer.",
    howUsed: "The singular 'they' for non-binary individuals — presented as a modern invention — is actually a return to centuries of English usage. Its recent politicization is about identity recognition, not grammatical innovation. As a third-person plural, 'they' is the pronoun of otherness — whoever is not us." },

  { word: "Tradition", category: "Not Classified",
    definition: "Wisdom passed down or refusal to change — context decides",
    phonetic: "trə·dish·ən",
    origin: "Latin <em>traditio</em> — a handing over, delivery. From <em>tradere</em> — to hand over, to deliver. Related to <em>traitor</em> — both involve handing something to someone else. Tradition is literally what has been handed down; a traitor is one who handed over what shouldn't have been.",
    howUsed: "G.K. Chesterton argued tradition is the democracy of the dead — giving a vote to ancestors. Critics argue traditions often preserve the preferences of those who had power when the tradition was established. 'Traditional values' as a political phrase refers to a specific recent construction, not an ancient one." },

  { word: "Truth", category: "Knowledge & Learning",
    definition: "Correspondence to fact, lived experience, or what power decides — rarely neutral",
    phonetic: "trooth",
    origin: "Old English <em>trēowth</em> — faithfulness, loyalty, the quality of being true. From <em>trēowe</em> — faithful, trustworthy. Truth was originally about fidelity to a person or promise — being true — before it became about correspondence to fact.",
    howUsed: "The shift from truth as fidelity to truth as factual accuracy tracks a larger shift in what we value in speech. 'Speaking your truth' reintroduces the personal, experiential sense of the word against the factual. 'Post-truth' describes a condition where neither the fidelity nor the factual sense has much grip." },

  { word: "Us", category: "Origins",
    definition: "The most loaded two-letter word in the language",
    phonetic: "us",
    origin: "Old English <em>ūs</em> — objective case of <em>wē</em> (we). Proto-Germanic. Among the oldest pronouns in the language. 'Us' is a relational word — it only means anything relative to 'them.'",
    howUsed: "'Us vs. them' is the most durable structure in political speech. The content of 'us' — who it includes, who it excludes — is the actual political argument. 'America First' is a claim about who counts as us. Every nationalist movement is a dispute about where the boundary falls." },

  { word: "Violence", category: "History & Civilization",
    definition: "Physical harm, structural harm, or the word used to shut down protest",
    phonetic: "vī·ə·ləns",
    origin: "Latin <em>violentia</em> — vehemence, force. From <em>violentus</em> — vehement, fierce. From <em>vis</em> — force, power. Related to <em>violate</em> — both involve force exceeding limits. The root connects to power and transgression simultaneously.",
    howUsed: "The definition of violence is itself political. Physical violence is rarely contested as violence; structural violence (poverty, inequality, denial of healthcare) is contested. The phrase 'violence begets violence' is used both to condemn protest and to explain rebellion. Who gets to name violence shapes who gets held accountable." },

  { word: "War", category: "History & Civilization",
    definition: "Defense, aggression, or policy — same act, opposite framings",
    phonetic: "wor",
    origin: "Old High German <em>werra</em> — strife, confusion. Replaced the Old English word <em>gewinn</em> after the Norman Conquest. The Germanic root meant confusion or strife more than organized military conflict — war as chaos rather than war as strategy.",
    howUsed: "'War on drugs,' 'war on poverty,' 'war on terror,' 'culture war' — the word has been extended metaphorically to describe any serious sustained effort. The metaphor carries consequences: it implies an enemy, it justifies emergency measures, and it makes failure into betrayal rather than policy inefficacy." },

  { word: "Wealth", category: "Power & Politics",
    definition: "Earned, inherited, extracted, or accumulated — rarely just one",
    phonetic: "welth",
    origin: "Middle English <em>welthe</em> — well-being, prosperity. From <em>weal</em> — well-being. Related to <em>well</em> and <em>welfare</em>. Originally meant general welfare and flourishing — not specifically monetary accumulation. The narrowing to financial wealth is a modern development.",
    howUsed: "The gap between 'wealth as flourishing' and 'wealth as money' is the gap that debates about inequality fall into. 'Wealth creation' implies general benefit — a rising tide. Critics argue that financial wealth accumulation can coexist with declining general welfare. The original meaning would not have understood the distinction." },

  { word: "Work", category: "Power & Politics",
    definition: "Dignity, exploitation, or identity — all three true simultaneously",
    phonetic: "wurk",
    origin: "Old English <em>weorc</em> — something done, labor, deed. Proto-Germanic. Related to the Greek <em>ergon</em> — work, deed (as in <em>energy</em>). Among the oldest words in the language — work needed naming before almost everything else.",
    howUsed: "'Hard work' is the foundational myth of American meritocracy — success is the reward for effort. The phrase functions to explain inequality as deserved outcome. The distinction between work (any human activity) and labor (work sold for wages) is made in Marxist theory and regularly collapsed in political speech." },

];

// ── Derived lookup for index.html glory highlights ──
// GLORIES = { "Word": "definition", ... }
const GLORIES = {};
GLORY_DATA.forEach(e => { GLORIES[e.word] = e.definition; });

// ── Derived glossary array for compendium.html ──
// glossary = [ { word, category, definition }, ... ]
const glossary = GLORY_DATA;
